apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

bases:
  - ../../base/installs/multi-user
  - ../../base/metadata/base
  - ../../base/metadata/options/istio
  - ../../third-party/argo/installs/cluster
  - ../../third-party/mysql/base
  - ../../third-party/mysql/options/istio
  - ../../third-party/metacontroller/base

generatorOptions:
  # mlpipeline-minio-artifact needs to be referred by exact name
  disableNameSuffixHash: true

configMapGenerator:
- name: pipeline-install-config
  env: pipeline-install-config.env
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config

secretGenerator:
- name: mlpipeline-minio-artifact
  env: object-store-secrets.env

patchesStrategicMerge:
- ntnx-config-patch.yaml

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

vars:
- name: kfp-artifact-storage-endpoint
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.objStoreHost
- name: kfp-artifact-storage-insecure
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.insecure